/**
 * Writes src/sip/stir-data.ts: an EXAMPLE P-256 key pair and the PASSporTs
 * of Module 28, signed with it. ECDSA signatures are random, so each run
 * writes different signatures; tests/stir.test.ts checks them all.
 * Run: node scripts/gen-stir.ts
 */
import fs from 'node:fs';
import { CALL_TIME, divHeader, divPayload, shakenHeader, shakenPayload, signPassport, SKEW, type Attest } from '../src/sip/stir.ts';

const pair = await crypto.subtle.generateKey({ name: 'ECDSA', namedCurve: 'P-256' }, true, ['sign', 'verify']) as CryptoKeyPair;
const pub = await crypto.subtle.exportKey('jwk', pair.publicKey);
const priv = await crypto.subtle.exportKey('jwk', pair.privateKey);
const strip = ({ key_ops: _k, ext: _e, ...k }: JsonWebKey) => k;

const tokens: Record<string, string> = {};
for (const a of ['A', 'B', 'C'] as Attest[]) {
  tokens[`${a}.ok`] = await signPassport(shakenHeader(), shakenPayload(a, CALL_TIME), priv);
  tokens[`${a}.skew`] = await signPassport(shakenHeader(), shakenPayload(a, CALL_TIME - SKEW), priv);
}
tokens['B.asA'] = await signPassport(shakenHeader(), { ...shakenPayload('B', CALL_TIME), attest: 'A' }, priv);
tokens.div = await signPassport(divHeader(), divPayload(CALL_TIME + 20), priv);

const out = `/**
 * GENERATED by scripts/gen-stir.ts. Do not edit.
 * An EXAMPLE key pair for the course, published on purpose: never use it for anything real.
 * In a real network, each carrier's signing service keeps its own private key secret,
 * and verifiers get the public key from the certificate at x5u.
 */
export const EXAMPLE_PUBLIC_JWK: JsonWebKey = ${JSON.stringify(strip(pub))};
export const EXAMPLE_PRIVATE_JWK: JsonWebKey = ${JSON.stringify(strip(priv))};
/** Full-form PASSporTs: "<attest>.ok" signed at the call time, "<attest>.skew" by a signer whose clock is 300 s slow, "B.asA" (B's number with A attestation), and "div". */
export const TOKENS: Record<string, string> = ${JSON.stringify(tokens, null, 2)};
`;
fs.writeFileSync(new URL('../src/sip/stir-data.ts', import.meta.url), out);
console.log('wrote src/sip/stir-data.ts with', Object.keys(tokens).length, 'tokens');
